### PR TITLE
(exa PR) 1141: git: Use GIT_DIR env var to find the repo

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/1141

### CODE REVIEW

**Comment by cafkafk** [comment]
see: https://github.com/ogham/exa/issues/722

**Comment by cafkafk** [comment]
I'm probably testing this wrong, but I'm not able to get this to work, @iamkroot would you be willing to demonstrate how I would test this (and or check if it's working after the merge)?

**Comment by iamkroot** [comment]
Even I'm not totally privy to all the git commands needed to replicate this. I have simply been using the git repo generated using [`yadm`](https://yadm.io) for backing up my dotfiles. So I'd suggest using that as a starting point. no need to track everything- 
1. you can just add a few files to stage
2. `export GIT_DIR=$HOME/.local/share/yadm/repo.git`
3. `cd /path/to/dir/with/staged/files`
4. `eza`

**Comment by iamkroot** [comment]
Tried locally- the patch is good. No compile issues, and works as expected.

**Pull request merged**
