### PR TITLE
(exa PR) 1188: Moving actions to dtolnay's version

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/1188

### CODE REVIEW

**Review by sbatial — APPROVED** [review]
@1stDimension's argument does make sense:
> Let's switch to dtolnay's version of [action](https://github.com/dtolnay/rust-toolchain). This route was taken [here](https://github.com/rust-lang/regex/commit/4cf7a347e8a1dc1127e922e9c02281f97939dcb5). It's code inside rust's regex crate. If it is good enough for them it will work for us.

And they are still using it today: https://github.com/rust-lang/regex/blob/master/.github/workflows/ci.yml#L80

I say we merge it and try to confirm that it does not break anything (the action does run on main anyways, no?)

I don't know if the checks for this PR would take the updated action if we merged main back into this branch but that would also be a viable option to have them run before going into main

**Comment by cafkafk** [comment]
> (the action does run on main anyways, no?)

Only one way to find out :D (we should get a development branch one of these days)

**Comment by cafkafk** [comment]
@sbatial https://github.com/cafkafk/eza/actions/runs/5707223523/workflow I think it did!

**Comment by sbatial** [comment]
Looks like it 👍

**Pull request merged**
