### PR TITLE
(exa PR) 370: Replace fixed colors by named ones so that it works well with any color scheme

### PR DESCRIPTION
**Pull request by cafkafk**
github.com/ogham/exa/pull/370

### CODE REVIEW

**Comment by sbatial** [comment]
Note:
```diff
- github.com/ogham/exa/pulls/370
+ github.com/ogham/exa/pull/370
```
is probably what you meant.

`ogham/exa/pull/370` (test: ogham/exa/pull/370) should also suffice to let github auto-link it

**Comment by sbatial** [comment]
looks fine to me. the code at least. I'm currently not able to compare the colors but will do so (probably later tonight. idk yet)

**Comment by cafkafk** [comment]
@sbatial you were correct, merging main triggered the workflow!

**Review by sbatial — APPROVED** [review]
looks better to me.

I feel like the color-scale of the sizes could maybe be improved. But it really wasn't any better before.

On exa mega and kilo numerals look very similar/the same to me.
After this change byte/kilobyte looks pretty similar

**Pull request merged**
