### PR TITLE
(exa PR) 1177: feature: hyperlink flag

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/1177

### CODE REVIEW

**Comment by cafkafk** [comment]
Refer to https://github.com/syphar/zetta/pull/6 for initial discussion

**Comment by cafkafk** [comment]
My local testing confirms this is working (very cool PR).

**Comment by cafkafk** [comment]
Also leaving a rope for people stuck on https://github.com/ogham/exa/issues/396

**Comment by plusgut** [comment]
that's so nice to see that this feature got implemented! Thanks a lot

**Pull request merged**
