### PR TITLE
(exa PR) 941: Show mounted filesystems and btrfs subvolumes

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/941

##### tests
- [ ] tests
- [ ] optionflag 
- [ ] documentation
- [ ] consider different output format

### CODE REVIEW

**Comment by cafkafk** [comment]
`cargo test` passes, this seems cool but perhaps it should be hidden behind a option flag?

**Comment by sbatial** [comment]
I like the idea as well.
I'd have to test it to give a final judgement.

But yes. I feel like this should be behind an option

Also: I don't see any new tests. It might make sense to add some for such a feature

**Comment by cafkafk** [comment]
> Also: I don't see any new tests. It might make sense to add some for such a feature

Agreed, needs tests, option and documentation.

**Comment by sbatial** [comment]
I have tested it and although I am a bit confused about the chosen rendering (the curly braces) it seems to work.

According to https://github.com/ogham/exa/issues/434#issuecomment-445176259 @ogham found it very useful as well back then so looking good so far

**Comment by cafkafk** [comment]
> although I am a bit confused about the chosen rendering (the curly braces)

Another thing to change before merging perhaps?

**Comment by sbatial** [comment]
@daviessm seems to be active on github so maybe they have any insight on why they did it that way

**Comment by daviessm** [comment]
This was the fist bit of Rust code I ever wrote, sorry if it's a bit strange. I'm open to changing any of the symbols used - I was awaiting feedback from the `exa` people. Particularly the flashing...

Regarding tests - is it possible to do tests without a btrfs filesystem?

I can add all of this in over the next few weeks if you give me some pointers.

**Comment by sbatial** [comment]
> Regarding tests - is it possible to do tests without a btrfs filesystem?

I'm not sure but I would say it could be given that the information would have to be a file or file attribute.
I would need to look deeper into this myself but it looks like the crate used has some tests of their own.

Maybe they help to gain more insight: https://github.com/pop-os/proc-mounts/blob/master/src/mounts/mod.rs

**Comment by daviessm** [comment]
Ok; should I start a new PR or should I submit a PR to this branch?

**Comment by cafkafk** [comment]
> Ok; should I start a new PR or should I submit a PR to this branch?

I'd actually prefer a new PR (that way I can add myself as a reviewer), bonus points if you follow https://www.conventionalcommits.org/en/v1.0.0/

**Comment by sbatial** [comment]
Closing in favor of new PR.

**Comment by daviessm** [comment]
New PR: #167

**Pull request closed without merging**
