### PR TITLE
(exa PR) 1136: Fix #393: add flag to dereference links

### LINKED ISSUE #393: ci: fails tests
- eza commit: tag `v0.13.0`
- Rust version: rustc 1.72.0 (5680fa18f 2023-08-23)
- Using Gentoo x86_64
- The Rust build target:
```
debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```

---

[build.log](https://github.com/eza-community/eza/files/12656095/build.log) on my machine

This was first reported in v0.12.0: https://bugs.gentoo.org/914214

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/1136

##### todo:
- [x] change commit messages to conventional commits
- [x] a quick trip through merge hell
- [x] add completions
- [ ] needs manual testing

### CODE REVIEW

**Comment by sbatial** [comment]
This has some overlap with #42 I think.
As in: #42 will probably be obsolete with this.

Output with relevant columns: (compare eza and result links)
| `eza -1l --no-user` | `eza -1Xl --no-user` |
|-|-|
|terminal output of 'eza -1l --no-user' | terminal output of 'eza -1Xl --no-user'|

**Comment by cafkafk** [comment]
> This has some overlap with #42 I think.

Yea, looks like merging is gonna get pretty hairy.

I do like how they have introduced a flag and documented it!

It does still need completions.

**Comment by cafkafk** [comment]
Can you check this out whenever you have time, it was a pretty big merge so I'd like to get more eyes on whether or not it's correct.

**Comment by sbatial** [comment]
I'm trying it out right now but it seems like it is deref'ing by default and the `-X` is not needed/does nothing?!
Is that possibly a bug on my end?
I pulled down to the newest beforehand.

**Comment by cafkafk** [comment]
> Is that possibly a bug on my end?

No I can reproduce it :s 

It shouldn't be hard to fix, I'll open an issue.

**Pull request merged**
