### PR TITLE
(exa PR) 1064: Add -A option for more compatibility with ls

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/1064

### CODE REVIEW

**Comment by sbatial** [comment]
I arrived at an implementation that does what we want and is pretty concise imo

One thing I'd like your opinion on: I think it makes sense to not err when `--tree --all --all` is used but to fall back to `--tree --all`.
I find it a bit pedantic for a tool to be very much _aware_ of the problem but not to try and react to it
(I'd do that in a different PR though. does not fall in the scope of this one)

**Comment by cafkafk** [comment]
> I think it makes sense to not err when `--tree --all --all` is used but to fall back to `--tree --all`.

I agree!

>  I find it a bit pedantic for a tool to be very much aware of the problem but not to try and react to it

Wym by this?

**Comment by cafkafk** [comment]
Your changes seem to work without breaking anything, and `cargo test` works. Testing the `-A` flag also seems to work for me.

Is this ready to merge?

**Comment by sbatial** [comment]
> > I find it a bit pedantic for a tool to be very much aware of the problem but not to try and react to it
>
> Wym by this?

Well when `--tree --all --all` is used right now an error is thrown that that is not possible.
But we know why it is not possible (as far as I'm aware): it would lead to infinite recursion.
And we also know a (imo) solution that is reasonable to assume that that is what the user tried to do.

**Review by sbatial — APPROVED** [review]

**Pull request merged**
