### PR TITLE
(exa PR) 1051: changed default folder icon

### PR DESCRIPTION
**Pull request by cafkafk**
https://github.com/ogham/exa/pull/1051

### CODE REVIEW

**Review by sbatial — COMMENTED** [review]
i don't care at the end of the day but would argue that an open folder makes more sense as the files inside the folder are (usually) shown

**Comment by cafkafk** [comment]
> i don't care at the end of the day but would argue that an open folder makes more sense as the files inside the folder are (usually) shown

That's the default behavior that this changes right? I can't actually see the icon this wants to change too, can you e.g. add a screenshot?

**Comment by sbatial** [comment]
image

Here's a side-by-side (or top-by-bottom rather?!)

**Comment by sbatial** [comment]
I kinda like both.
It would be nice to have them actually indicate folders which are recursed into... But I don't know how much work that'll be and is not in the scope of this PR

**Comment by cafkafk** [comment]
> I kinda like both. It would be nice to have them actually indicate folders which are recursed into

I guess in that case this PR would be the default, so it makes sense to merge and e.g. create an issue for that (it's a good idea imo)

**Review by sbatial — APPROVED** [review]
Good default.
See #92 for follow-up

**Pull request merged**
